---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          command: |
            pipenv run pytest
      - run:
          command: |
            isort -rc .
      - run:
          command: |
            yapf --style=google -dr .
      - run:
          command: |
            docs/make html


commands:
  is_docs_update:
    steps:
      - run:
          name: check tests folder is updated
          command: |
            if [[ ! $(git diff --diff-filter=d --name-only HEAD | grep tests/ ) = '' ]]; then
              echo "build and deploy"
            else
                echo "deploy not needed for << parameters.pattern >> workflow"
                circleci step halt
            fi
      - run:
          name: make rst file
          command: |
            sphinx-apidoc -F -o docs/ tests/
      - run:
          name: make html
          command: |
            make html
