version: 2.1

executors:
  python-exec:
    docker:
      - image: circleci/python:3.8.2
    environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  setup_environment:
    steps:  
      - checkout
      - run:
          name: set up environment
          command: |
            sudo pip install pipenv
            pipenv install --dev

  is_docs_update:
    steps:
      - run:
          name: check tests folder is updated
          command: |
            if [[ ! $(git diff --diff-filter=d --name-only HEAD | grep tests/ ) = '' ]]; then
              echo "build and deploy"
            else
                echo "no need docs update"
                circleci step halt
            fi
      - run:
          name: make rst file
          command: |
            pipenv run sphinx-apidoc -f -o docs/ tests/
      - run:
          name: make html
          command: |
            pipenv run sphinx-build -a ./docs ./docs/public
      - run:
          name: git push
          command: | 
            git config --global user.email oxkeita@gmail.com
            git config --global user.name odrum428
            git add -A
            git commit -m 'updating docs [skip ci]'
            git push origin HEAD

jobs:
  style_check:
    executor: python-exec
    steps:
      - setup_environment
      - run:
          name: check package order
          command: |
            pipenv run isort -rc .
      - run:
          name: check code style
          command: |
            pipenv run flake8 .
  
  code_test:
    executor: python-exec
    steps:
      - setup_environment
      - run:
          name: run pytest
          command: |
            pipenv run pytest

  docs_update:
    executor: python-exec
    steps:
      - setup_environment
      - is_docs_update

workflows:
  basic_workflow:
    jobs:
      - style_check
      - code_test:
          requires:
            - style_check
      - docs_update:
          requires:
            - code_test
